language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 on:
   repo: afurerucolors/afurerucolors@github.io
   branch: main
   tags: true