export default {
    namespaced: true,
    state: {
        contactPersons: [{
            name: "Instagram",
            account: "@afurerucolors",
            link: "https://www.instagram.com/afurerucolors",
            icon: "mdi-instagram",
        },
        {
            name: "Twitter",
            account: "@afurerucolors",
            link: "https://www.twitter.com/afurerucolors",
            icon: "mdi-twitter",
        },
        {
            name: "Email",
            account: "afurerucolors@gmail.com",
            link: "",
            icon: "mdi-email",
        },
            // {
            //     name: "Whatsapp",
            //     account: "+62-853-5066-2800",
            //     link: "https://wa.me/+6285350662800",
            //     icon: "mdi-whatsapp",
            // },
        ],
        socialMedias: [{
            name: "Pixiv",
            account: "Afureru Colors",
            link: "https://www.pixiv.net/users/35822162",
            icon: null,
            src: "pixiv",
            platformsrc: "pixiv-blue",
            background: "blue lighten-5",
            text: "blue--text text--darken-2",
            quicklink: true,
        },
        {
            name: "Twitter",
            account: "@afurerucolors",
            link: "https://www.twitter.com/afurerucolors",
            icon: "mdi-twitter",
            background: "blue lighten-4",
            text: "blue--text text--darken-3",
            quicklink: true,
        },
        {
            name: "Instagram",
            account: "@afurerucolors",
            link: "https://www.instagram.com/afurerucolors",
            icon: "mdi-instagram",
            background: "red lighten-5",
            text: "purple--text text--darken-4",
            quicklink: true,
        },
        {
            name: "Facebook",
            account: "Afureru Colors",
            link: "https://www.facebook.com/afurerucolors",
            icon: "mdi-facebook",
            background: "blue-grey lighten-5",
            text: "blue--text text--darken-4",
        },
        {
            name: "DeviantArt",
            account: "AfureruColors",
            link: "https://www.deviantart.com/afurerucolors",
            icon: "mdi-deviantart",
            background: "grey lighten-2",
            text: "green--text text--darken-4",
            quicklink: true,
        },
        {
            name: "Artstation",
            account: "Afureru Colors",
            link: "https://www.artstation.com/afurerucolors",
            icon: "mdi-artstation",
            background: "indigo lighten-4",
            text: "indigo--text text--darken-4",
            quicklink: true,
        },
       
        {
            name: "Sketchmob",
            account: "Afureru Colors",
            link: "https://sketchmob.com/user-profile/afurerucolors",
            icon: 'mdi-lead-pencil',
            // hide: true,
            // disabled: true,
            // background: "amber lighten-5",
            // text: "indigo--text text--lighten-4",
            background: "amber lighten-3",
            text: "indigo--text text--lighten-1",
        },
        {
            name: "Fiverr",
            account: "Afureru Colors",
            link: "https://www.fiverr.com/afurerucolors",
            icon: 'mdi-pen',
            // hide: true,
            // disabled: true,
            // background: "blue-grey lighten-5",
            // text: "green--text text--lighten-3",
            background: "green lighten-4",
            text: "green--text text--darken-4",
        },
        {
            name: "Website",
            account: "Afureru Colors",
            link: "/",
            website: true,
            icon: 'mdi-web',
            background: "teal lighten-4",
            text: "teal--text text--darken-4",

        },
        ],
    }

}